# Generated by Django 4.1.2 on 2023-03-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='key',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
