# Generated by Django 4.1.2 on 2023-03-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_size_variation'),
        ('cart', '0002_alter_cartitem_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='products.variation'),
        ),
    ]
