# Generated by Django 4.1.2 on 2023-04-21 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_size_variation'),
        ('orders', '0002_rename_paument_order_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.variation'),
        ),
    ]
