# Generated by Django 4.1.2 on 2023-04-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_reviewsrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewsRating',
        ),
    ]
