# Generated by Django 4.1.2 on 2023-03-03 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='add_category',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.productcategory'),
        ),
        migrations.DeleteModel(
            name='AdditionalProductCategory',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
