# Generated by Django 4.1.2 on 2023-05-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_reviewsrating_remove_reviews_product_delete_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsrating',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
